version: '3'

services:
  influxdb-dev:
    image: influxdb:2.6-alpine
    env_file:
      - influx.env
    volumes:
      - ./data:/var/lib/influxdb2:rw
      - ./config:/etc/influxdb2:rw
    ports:
      - "8087:8086"
    networks:
      - wilga-vm-network

  grafana-dev:
    image: grafana/grafana:9.3.4
    env_file:
      - grafana.env
    volumes:
      - ./grafana-storage:/var/lib/grafana:rw
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/grafana-datasources.yaml:ro
    ports:
      - 3001:3000
    networks:
      - wilga-vm-network
    user: "1000"

  telegraf-dev:
    image: telegraf:1.29.2
    env_file:
      - telegraf.env
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - "8095:8094"
    networks:
      - wilga-vm-network

networks:
  wilga-vm-network:
    external: true